<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Name</name>
   <tag></tag>
   <elementGuidId>6e34a0c2-897e-4b3f-9f23-546d3c670d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/following::label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.block.text-sm.font-medium.text-gray-700</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>22040519-4b9c-4c8a-8d74-173ff10b0fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>181b0113-f74a-4b23-881d-22b31e2a4588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block text-sm font-medium text-gray-700</value>
      <webElementGuid>e0a40301-76a6-4d17-a448-d40b8678a77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>67412e55-0c2d-43a9-b5ed-f79dd59f578b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;font-sans text-gray-900 antialiased&quot;]/div[@class=&quot;min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;max-w-md w-full space-y-8&quot;]/div[@class=&quot;rounded bg-white max-w-md rounded overflow-hidden shadow-xl p-5&quot;]/form[@class=&quot;space-y-4&quot;]/div[@class=&quot;rounded-md shadow-sm -space-y-px&quot;]/div[@class=&quot;grid gap-6&quot;]/div[@class=&quot;col-span-12&quot;]/label[@class=&quot;block text-sm font-medium text-gray-700&quot;]</value>
      <webElementGuid>dec1f2e8-48b8-42f5-a901-b600ea1409f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b5551a3-97c7-48ee-b2f7-5f8e8ebf7ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>2bb0a57f-6896-458c-8c05-57bda344a439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block text-sm font-medium text-gray-700</value>
      <webElementGuid>ef63d917-09cd-4134-82d9-26864141af8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c8ac34ae-82e8-48ee-815c-10044cfc4036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;font-sans text-gray-900 antialiased&quot;]/div[@class=&quot;min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;max-w-md w-full space-y-8&quot;]/div[@class=&quot;rounded bg-white max-w-md rounded overflow-hidden shadow-xl p-5&quot;]/form[@class=&quot;space-y-4&quot;]/div[@class=&quot;rounded-md shadow-sm -space-y-px&quot;]/div[@class=&quot;grid gap-6&quot;]/div[@class=&quot;col-span-12&quot;]/label[@class=&quot;block text-sm font-medium text-gray-700&quot;]</value>
      <webElementGuid>dbba3363-eb25-4c55-b031-bdb401631321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/following::label[1]</value>
      <webElementGuid>57547ea5-734f-4d21-8deb-7bdcf4fb8836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/preceding::label[1]</value>
      <webElementGuid>3aaf4a49-d678-4029-966d-fde18bf1ac74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/preceding::label[2]</value>
      <webElementGuid>228bd4bc-be4d-4977-aaba-8a0ec315e759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name']/parent::*</value>
      <webElementGuid>046407fa-d45d-47c4-8899-1957144f02f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>40cb697b-c070-40c3-a84d-122db43d1f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>c80f8a62-d2cf-4444-a0c4-eaa52ec0c14b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
